runtime: custom
env: flex

service_account: flask-sql-access@refined-graph-458003-m5.iam.gserviceaccount.com

env_variables:
  ENV: "test"

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10